apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-oidc-proxy
  namespace: oidc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-oidc-proxy
  template:
    metadata:
      labels:
        app: kube-oidc-proxy
    spec:
      containers:
      - name: proxy
        image: ghcr.io/tremolosecurity/kube-oidc-proxy:latest
        command:
        - /usr/bin/kube-oidc-proxy
        args:
        - --bind-address=0.0.0.0
        - --secure-port=8443
        - --oidc-issuer-url=http://dex.auth.svc.cluster.local:5556
        - --oidc-client-id=cli
        - --oidc-ca-file=/dev/null
        - --disable-impersonation=true
        - --insecure-skip-tls-verify=true
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-proxy
  namespace: oidc-proxy
spec:
  selector:
    app: kube-oidc-proxy
  ports:
  - port: 8443
    targetPort: 8443

